mariadb:
  architecture: "standalone"
  auth:
    existingSecret: "mariadb-credentials"

  primary:
    extraFlags: >-
      --skip-character-set-client-handshake
      --skip-innodb-read-only-compressed
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    service:
      type: LoadBalancer

  tls:
    enabled: true  # Asegúrate de que esté habilitado
    existingSecret: tls-cert  # Usa el secreto TLS correcto