mariadb:
  architecture: "standalone"
  auth:
    existingSecret: "mariadb-credentials"
             
  primary:
    extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    persistence:
      enabled: true
      storageClass: "nfs"
      accessMode: ReadWriteMany
      accessModes:
        - ReadWriteMany
      size: 8Gi

  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    hostname: mariadb.mabecenter.org
    extraTls:
      - hosts:
          - "mariadb.mabecenter.org"
        secretName: tls-cert
    annotations:
      kubernetes.io/ingress.class: "traefik"
      kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls: true
  
  tls:
    enabled: true
    existingSecret: tls-cert