mariadb:
  architecture: "standalone"
  auth:
    existingSecret: "mariadb-credentials"

  primary:
    extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"

  ingress:
    enabled: true  # Asegúrate de que esté habilitado
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    hostname: mariadb.mabecenter.org
    pathType: Prefix  # Asegúrate de que el pathType sea adecuado
    extraTls:
      - hosts:
          - "mariadb.mabecenter.org"
        secretName: tls-cert  # Usa el nombre del secreto correcto para el TLS
    annotations:
      kubernetes.io/ingress.class: "traefik"
      kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls: true

  tls:
    enabled: true  # Asegúrate de que esté habilitado
    existingSecret: tls-cert  # Usa el secreto TLS correcto
