mariadb:
  architecture: "standalone"
  auth:
    existingSecret: "mariadb-credentials"

  primary:
    extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    configuration:

  tls:
    enabled: true  # Asegúrate de que esté habilitado
    existingSecret: tls-cert  # Usa el secreto TLS correcto