mariadb:
  architecture: "standalone"

  primary:
    extraFlags: >-
      --skip-character-set-client-handshake
      --skip-innodb-read-only-compressed
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    extraEnvVars:
      - name: MARIADB_REQUIRE_SECURE_TRANSPORT
        value: "OFF"  

  auth:
    database: sync
    existingSecret: "mariadb-credentials"
    secretKeys:
        adminPasswordKey: "mariadb-root-password"
        userPasswordKey: "mariadb-password"
        replicationPasswordKey: "mariadb-replication-password"
  
  tls:
    enabled: false
  
  volumePermissions:
    enabled: true