mariadb:
  architecture: "standalone"
  auth:
    existingSecret: "mariadb-credentials"
             
  primary:
    extraFlags: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin"

  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.tcp.routers.mariadb.entrypoints: "mariadb"  # Definir el entrypoint TCP.
      traefik.tcp.routers.mariadb.rule: "HostSNI(`*`)"  # Reglas de SNI para el host.
      traefik.tcp.routers.mariadb.tls: "true"
      traefik.tcp.routers.mariadb.service: "mariadb"
      traefik.tcp.services.mariadb.loadbalancer.server.port: "3306"
    tls:
      - secretName: tls-cert  # Certificado TLS para la conexión segura
